In [46]:
import pandas as pd

In [47]:
train = pd.read_csv("./train.csv")

In [48]:
#renombramos las columnas
train.rename(columns={'carat': 'quilates','cut':'calidad corte','depth':'porcentaje profundidad','table': 'ancho superior','x':'longitud mm','y':'ancho mm','z':'profundidad mm'},inplace=True)

In [49]:
#comprobamos que no hay valores nulos.
train.isnull().sum()

id                        0
quilates                  0
calidad corte             0
color                     0
clarity                   0
porcentaje profundidad    0
ancho superior            0
longitud mm               0
ancho mm                  0
profundidad mm            0
price                     0
dtype: int64

In [50]:
#comprobamos que no hay valores de cero
train.describe() #observamos que efectiamente hay ceros en longitud, ancho y profundidad.

,id,quilates,porcentaje profundidad,ancho superior,longitud mm,ancho mm,profundidad mm,price
count,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000
mean,20227.000000,0.800571,61.749675,57.462820,5.737267,5.741070,3.541966,3956.020517
std,11678.496907,0.475258,1.433896,2.243808,1.123680,1.153677,0.696327,4009.646467
min,0.000000,0.200000,43.000000,43.000000,0.000000,0.000000,0.000000,326.000000
25%,10113.500000,0.400000,61.000000,56.000000,4.720000,4.730000,2.910000,954.000000
50%,20227.000000,0.700000,61.800000,57.000000,5.700000,5.710000,3.530000,2428.000000
75%,30340.500000,1.050000,62.500000,59.000000,6.540000,6.540000,4.040000,5362.500000
max,40454.000000,5.010000,79.000000,95.000000,10.740000,58.900000,8.060000,18818.000000

In [51]:
train[train==0].count() #6 en longitud y ancho, y 15 en profundidad.

id                         1
quilates                   0
calidad corte              0
color                      0
clarity                    0
porcentaje profundidad     0
ancho superior             0
longitud mm                6
ancho mm                   6
profundidad mm            15
price                      0
dtype: int64

In [52]:
#vamos a sustituir los ceros por valores predichos. y para ello vamos a importar unas cuantas librerias.
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

**prediccion profundidad**

In [53]:
lr_profundidad = LinearRegression()

In [54]:
X_train, X_test, y_train, y_test = train_test_split(train[["quilates","ancho superior"]],train["profundidad mm"],train_size =0.8,test_size = 0.2)

In [55]:
modelo_profundidad = lr_profundidad.fit(X_train,y_train)
y_pred_profts = modelo_profundidad.predict(X_test) #predecimos la prueba
y_pred_proftr =modelo_profundidad.predict(X_train) #predecimos el entrenamiento

In [56]:
profundidad_predicha_ts = pd.DataFrame({"real":y_test,"pred":y_pred_profts})
profundidad_predicha_tr = pd.DataFrame({"real":y_train,"pred":y_pred_proftr})

In [57]:
#comprobamos en que filas los valores son ceros.
train[train["profundidad mm"]==0]

,id,quilates,calidad corte,color,clarity,porcentaje profundidad,ancho superior,longitud mm,ancho mm,profundidad mm,price
2365,2365,0.71,Good,F,SI2,64.1,60.0,0.00,0.00,0.0,2130
2572,2572,1.56,Ideal,G,VS2,62.2,54.0,0.00,0.00,0.0,12800
3276,3276,1.00,Very Good,H,VS2,63.3,53.0,0.00,0.00,0.0,5139
10241,10241,2.80,Good,G,SI2,63.8,58.0,8.90,8.85,0.0,18788
18199,18199,2.20,Premium,H,SI1,61.2,59.0,8.42,8.37,0.0,17265
22522,22522,1.15,Ideal,G,VS2,59.2,56.0,6.88,6.83,0.0,5564
23323,23323,1.20,Premium,D,VVS1,62.1,59.0,0.00,0.00,0.0,15686
24049,24049,1.10,Premium,G,SI2,63.0,59.0,6.50,6.47,0.0,3696
24409,24409,2.18,Premium,H,SI2,59.4,61.0,8.49,8.45,0.0,12631
26171,26171,1.01,Premium,F,SI2,59.2,58.0,6.50,6.47,0.0,3837
27742,27742,2.02,Premium,H,VS2,62.7,53.0,8.02,7.95,0.0,18207
29257,29257,1.14,Fair,G,VS1,57.5,67.0,0.00,0.00,0.0,6381
30240,30240,0.71,Good,F,SI2,64.1,60.0,0.00,0.00,0.0,2130
38260,38260,2.25,Premium,I,SI1,61.3,58.0,8.52,8.42,0.0,15397
38590,38590,1.00,Premium,G,SI2,59.1,59.0,6.55,6.48,0.0,3142

In [85]:
print(profundidad_predicha_ts.loc[2365])
print("-----")
print(profundidad_predicha_tr.loc[2572])
print("-----")
print(profundidad_predicha_tr.loc[3276])
print("-----")
print(profundidad_predicha_tr.loc[23323])
print("------")
print(profundidad_predicha_tr.loc[29257])
print("--------")
print(profundidad_predicha_tr.loc[30240])
print("--------------------")
print(profundidad_predicha_tr.loc[10241])
print("-----")
print(profundidad_predicha_tr.loc[18199])
print("-----")
print(profundidad_predicha_tr.loc[22522])
print("-----")

print("------")
print(profundidad_predicha_tr.loc[24049])
print("--------")
print(profundidad_predicha_tr.loc[26171])
print("-----")
print(profundidad_predicha_tr.loc[27742])
print("-----")
print(profundidad_predicha_tr.loc[38260])
print("------")
print(profundidad_predicha_tr.loc[38590])
print("--------")
print(profundidad_predicha_ts.loc[24409])

real    0.000000
pred    3.395551
Name: 2365, dtype: float64
-----
real    0.000000
pred    4.645318
Name: 2572, dtype: float64
-----
real    0.000000
pred    3.855618
Name: 3276, dtype: float64
-----
real    0.000000
pred    4.099287
Name: 23323, dtype: float64
------
real    0.000000
pred    3.959555
Name: 29257, dtype: float64
--------
real    0.000000
pred    3.395551
Name: 30240, dtype: float64
--------------------
real    0.000000
pred    6.381799
Name: 10241, dtype: float64
-----
real    0.000000
pred    5.521608
Name: 18199, dtype: float64
-----
real    0.000000
pred    4.048569
Name: 22522, dtype: float64
-----
------
real    0.000000
pred    3.957055
Name: 24049, dtype: float64
--------
real    0.000000
pred    3.835845
Name: 26171, dtype: float64
-----
real    0.000000
pred    5.306385
Name: 27742, dtype: float64
-----
real    0.000000
pred    5.599523
Name: 38260, dtype: float64
------
real    0.000000
pred    3.814823
Name: 38590, dtype: float64
--------
real    0.000000
pred    5.479563
Name: 24409, dtype: float64

In [86]:
def insertar_valor(columna,fila,valor): #definimos una funcion para insertar datos en las columnas
    train[columna].loc[fila]= valor
    return train[columna].loc[fila]

#insertar_valor("profundidad mm",24409,5.479563)

C:\Users\Adrian\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

5.479563

In [87]:
train[train["profundidad mm"]==0] #vemos que no tenemos ya valores de cero.

Empty DataFrame
Columns: [id, quilates, calidad corte, color, clarity, porcentaje profundidad, ancho superior, longitud mm, ancho mm, profundidad mm, price]
Index: []

**prediccion ancho**

In [88]:
X_train, X_test, y_train, y_test = train_test_split(train[["quilates","ancho superior"]],train["ancho mm"],train_size =0.8,test_size = 0.2,random_state = 42)

In [89]:
lr_ancho = LinearRegression()
model_ancho = lr_ancho.fit(X_train,y_train)
pred_anchotr = model_ancho.predict(X_train) #prediccion entrenamiento
pred_anchots = model_ancho.predict(X_test) #prediccion prueba
ancho_predicha_tr = pd.DataFrame({"real":y_train,"pred":pred_anchotr})
ancho_predicha_ts = pd.DataFrame({"real":y_test,"pred":pred_anchots})

In [90]:
print(ancho_predicha_tr.loc[2365])
print("-----")
print(ancho_predicha_tr.loc[2572])
print("-----")
print(ancho_predicha_tr.loc[3276])
print("-----")
print(ancho_predicha_tr.loc[23323])
print("------")
print(ancho_predicha_tr.loc[29257])
print("--------")
print(ancho_predicha_tr.loc[30240])
#lo  mismo que con la profundidad

real    0.000000
pred    5.548565
Name: 2365, dtype: float64
-----
real    0.000000
pred    7.462142
Name: 2572, dtype: float64
-----
real    0.000000
pred    6.172931
Name: 3276, dtype: float64
-----
real    0.000000
pred    6.665835
Name: 23323, dtype: float64
------
real    0.000000
pred    6.574357
Name: 29257, dtype: float64
--------
real    0.000000
pred    5.548565
Name: 30240, dtype: float64

In [96]:
#insertar_valor("ancho mm",30240,5.548565)

5.548565

In [97]:
train[train["ancho mm"]==0] #tampoco hay valores de cero en ancho.

Empty DataFrame
Columns: [id, quilates, calidad corte, color, clarity, porcentaje profundidad, ancho superior, longitud mm, ancho mm, profundidad mm, price]
Index: []

**prediccion de longitud**

In [98]:
lr_longitud = LinearRegression()

In [99]:
mode_longitud = lr_longitud.fit(X_train,y_train)

In [100]:
pred_lontr = mode_longitud.predict(X_train) #prediccion entrenamiento
pred_lonts = mode_longitud.predict(X_test) #prediccion prueba

In [101]:
lon_predicha_tr = pd.DataFrame({"real":y_train,"pred":pred_lontr})
lon_predicha_ts = pd.DataFrame({"real":y_test,"pred":pred_lonts})

In [102]:
print(lon_predicha_tr.loc[2365])
print("-----")
print(lon_predicha_tr.loc[2572])
print("-----")
print(lon_predicha_tr.loc[3276])
print("-----")
print(lon_predicha_tr.loc[23323])
print("------")
print(lon_predicha_tr.loc[29257])
print("--------")
print(lon_predicha_tr.loc[30240])
#lo  mismo que con la profundidad y ancho.

real    0.000000
pred    5.548565
Name: 2365, dtype: float64
-----
real    0.000000
pred    7.462142
Name: 2572, dtype: float64
-----
real    0.000000
pred    6.172931
Name: 3276, dtype: float64
-----
real    0.000000
pred    6.665835
Name: 23323, dtype: float64
------
real    0.000000
pred    6.574357
Name: 29257, dtype: float64
--------
real    0.000000
pred    5.548565
Name: 30240, dtype: float64

In [108]:
#insertar_valor("longitud mm",30240,5.548565)

5.548565

In [109]:
train[train["longitud mm"]==0] #tampoco hay en longitud

Empty DataFrame
Columns: [id, quilates, calidad corte, color, clarity, porcentaje profundidad, ancho superior, longitud mm, ancho mm, profundidad mm, price]
Index: []

In [110]:
train.describe() #ya no tenemos valores de cero en  ninguna columna.

,id,quilates,porcentaje profundidad,ancho superior,longitud mm,ancho mm,profundidad mm,price
count,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000,40455.000000
mean,20227.000000,0.800571,61.749675,57.462820,5.738205,5.742009,3.543629,3956.020517
std,11678.496907,0.475258,1.433896,2.243808,1.121558,1.151608,0.693431,4009.646467
min,0.000000,0.200000,43.000000,43.000000,3.730000,3.710000,1.070000,326.000000
25%,10113.500000,0.400000,61.000000,56.000000,4.720000,4.730000,2.910000,954.000000
50%,20227.000000,0.700000,61.800000,57.000000,5.700000,5.710000,3.530000,2428.000000
75%,30340.500000,1.050000,62.500000,59.000000,6.540000,6.540000,4.040000,5362.500000
max,40454.000000,5.010000,79.000000,95.000000,10.740000,58.900000,8.060000,18818.000000

In [117]:
train.to_csv("./train_limpio.csv")